basurl = "https://jovany-vergara.github.io/"
languageCode = "en-us"
title = "Jovany Vergara"
theme = "m10c"

[params]
  author = "Jovany Vergara"
  description = "I'm Developer"
  menu_item_separator = " - "
  avatar = "/yo1.jfif"


[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/Jovany-Vergara"

   [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/MR_Wolverine114"
